#! /bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🚀 Starting linting and formatting checks..."

npx lint-staged

if [ $? -eq 0 ]; then
  echo "✅ Linting and formatting successful! All checks passed."
else
  echo "⛔️ Linting or formatting failed. Please fix the issues and try again."
  exit 1
fi
